fix lite

diff --git a/Dockerfile.lite b/Dockerfile.lite
--- a/Dockerfile.lite
+++ b/Dockerfile.lite
@@ -9,10 +9,38 @@ RUN mkdir /app/ && mv /kvs/kvs /kas/kas /app/
 
 FROM debian:trixie-slim
 
-RUN apt-get update && apt-get install -y \
-    ca-certificates curl openssh-client openssh-server &&\
+RUN apt update && DEBIAN_FRONTEND=noninteractive \
+    apt install --no-install-recommends -y \
+    ca-certificates git zsh bash sudo wget curl nano jq \
+    locales tzdata util-linux iputils-ping net-tools \
+    openssh-client openssh-server \
+    powerline-go \
+    zsh-autosuggestions \
+    zsh-syntax-highlighting \
+    fontconfig \
+    fonts-noto-core \
+    fonts-noto-cjk \
+    fonts-noto-color-emoji \
+    fonts-powerline && \
+    fc-cache -f -v && \
+    sed -i 's/^# zh_CN.UTF-8/zh_CN.UTF-8/' /etc/locale.gen &&\
+    sed -i 's/^# C.UTF-8/C.UTF-8/' /etc/locale.gen &&\
+    locale-gen zh_CN.UTF-8 C.UTF-8 && \
+    echo 'precmd_functions+=( f ) && f() { PS1="$(powerline-go -error $? -shell zsh -cwd-max-depth 1 -cwd-mode dironly -modules time,cwd,git,exit)"; }' >> ~/.zshrc && \
+    echo "source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh" >> ~/.zshrc && \
+    echo "# source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ~/.zshrc && \
+    chsh -s /usr/bin/zsh && \
     apt-get autoremove && apt-get clean && \
     rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*
+    
+# set environment variables
+ENV LANGUAGE="zh_CN:zh" \
+    LANG="zh_CN.UTF-8" \
+    LC_ALL="zh_CN.UTF-8" \
+    LC_CTYPE="zh_CN.UTF-8"
+
+# 将默认 locale 写入 /etc/default/locale，避免 setlocale 警告
+RUN echo 'LANG=zh_CN.UTF-8\nLC_ALL=zh_CN.UTF-8\nLC_CTYPE=zh_CN.UTF-8\nLANGUAGE=zh_CN:zh' > /etc/default/locale
 
 # set environment variables
 ENV KAS_SSHD="0" \
