fix proxypod

diff --git a/rootfs/usr/local/bin/agent-chrome b/rootfs/usr/local/bin/agent-chrome
--- a/rootfs/usr/local/bin/agent-chrome
+++ b/rootfs/usr/local/bin/agent-chrome
@@ -2,12 +2,53 @@
 
 set -e
 
-# 如果 $HOME/browsers/chrome 目录不存在，则创建
-if [ ! -d "$HOME/browsers/chrome" ]; then
-    mkdir -p $HOME/browsers/chrome
+
+# 初始化参数变量
+name="chrome"
+port=9222
+host="0.0.0.0"
+data=""
+
+
+# 使用 getopts 解析参数
+while getopts "n:p:h:d:" opt; do
+    case ${opt} in
+        n)
+            name=$OPTARG
+            ;;
+        p)
+            port=$OPTARG
+            ;;
+        h)
+            host=$OPTARG
+            ;;
+        d)
+            data=$OPTARG
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
+        :)
+            echo "Option -$OPTARG requires an argument." >&2
+            exit 1
+            ;;
+    esac
+done
+
+# 检查工作目录是否存在
+if [ -z "${data}" ]; then
+    data="$HOME/.cache/$name"
+fi
+if [ ! -d "$data" ]; then
+    mkdir -p $data
 fi
 
-google-chrome --user-data-dir=$HOME/browsers/chrome \
+# 启动浏览器
+google-chrome \
+--user-data-dir=$data \
+--remote-debugging-port=$port \
+--remote-debugging-address=$host \
 --window-position=0,0 \
 --start-maximized \
 --disable-dev-shm-usage \
@@ -16,6 +57,4 @@ google-chrome --user-data-dir=$HOME/browsers/chrome \
 --no-first-run \
 --no-default-browser-check \
 --no-experiments \
---remote-debugging-port=9222 \
---remote-debugging-address=0.0.0.0 \
 "http://127.0.0.1:7788"
